language: java

jdk:
  - openjdk16

sudo: false

env:
  global:
    - CODECOV_TOKEN="a8926229-fdab-4cc7-a207-068fc9d7e3d2"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      -rail.anuta_myrzilka@inbox.ru
    on_success: never # default: change
    on_failure: always # default: always